### ISSUE TITLE
Fix broken builds

### ISSUE THREAD

**Issue by Abhirup-99** [EOS-uiux-Solutions/user-story#116]
## Fix the Github CI builds.

**Comment by kailash360** [comment]
@Abhirup-99 

The CI/CD is apparently failing because the dependencies are failing to install. The [github-ci.yml](https://github.com/EOS-uiux-Solutions/user-story/blob/main/.github/workflows/github-ci.yml) file has no NodeJS version specified. As the `README.md`  suggests, it needs `NodeJS 13.x.x` only to run. So, specifying the version can solve this issue.

However, following PR #115, the dependencies are upgraded to latest version. So, they can be installed safely and the build will not fail (if all tests pass).

**Comment by kailash360** [comment]
@Abhirup-99 
The error seems to generate because the dependencies fail to install during the build. This happens because `NodeJS 13.x.x` is required during installation, which is not specified in the CI file.

Can I proceed to work on this issue?
